import "./globals.css";
import NavWrapper from "./NavWrapper";
import { MenuProvider } from "../context/MenuContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <MenuProvider>
          <NavWrapper />
          {children}
        </MenuProvider>
      </body>
    </html>
  );
}
